### ISSUE TITLE
other browser ?

### ISSUE THREAD

**Issue by thorin31** [oblador/hush#48]
It'w be very interesting to port this amazing module on other browser like Firefox ;)

**Comment by jasperweiss** [comment]
I think [I don't care about cookies](https://www.i-dont-care-about-cookies.eu) already fills that gap. I think hush is mainly created because Safari on iOS requires the use of content blockers. Content blockers are also nicer in general since they don't require permission to view your browsing activity and instead delegate the task of blocking things to the browser itself which may also be more efficient. 
Chrome and Firefox don't have content blockers and the extension would have to be rewritten from scratch since Swift is not supported there either. At that point you're essentially just creating a clone of https://www.i-dont-care-about-cookies.eu
